/** Maps content icon names (kebab-case strings in JSON) to generic lucide icons. */
import type { LucideIcon, LucideProps } from 'lucide-react'
import { azureIconUrl, isAzureIcon } from '@/content/azureIcons'
import {
  GraduationCap,
  Shuffle,
  CircleCheck,
  Compass,
  CircleX,
  CalendarDays,
  Timer,
  Printer,
  Sparkles,
  TrendingUp,
  ShieldCheck,
  Database,
  Server,
  Network,
  Activity,
  Users,
  User,
  UserCog,
  Key,
  KeyRound,
  Lock,
  Tag,
  Tags,
  Wallet,
  Coins,
  FolderTree,
  Folder,
  Layers,
  Cloud,
  HardDrive,
  Globe,
  Router,
  Split,
  Scale,
  Shield,
  ShieldAlert,
  Eye,
  Bell,
  Archive,
  RefreshCw,
  Box,
  Boxes,
  Container,
  AppWindow,
  Cpu,
  GitBranch,
  Map,
  LifeBuoy,
  FileText,
  Workflow,
  Building,
  Building2,
  Landmark,
  Gauge,
  Brain,
  Flame,
  Target,
  Clock,
  Zap,
  Waypoints,
  Cable,
  Route,
  Radar,
  ScanSearch,
  ServerCog,
  DatabaseBackup,
  HardDriveDownload,
  CloudCog,
  Fingerprint,
  IdCard,
  BadgeCheck,
  ScrollText,
  Ban,
  Signpost,
  SquareStack,
  MapPin,
  LockKeyhole,
  FileKey,
  Link2,
  Repeat,
  Gavel,
  CircleDollarSign,
  Antenna,
  PlugZap,
  Unplug,
  Grid2x2,
  Spline,
  Monitor,
  Lightbulb,
  TriangleAlert,
  BookOpen,
  Laptop,
  Smartphone,
  Mail,
  Webhook,
  Settings,
  Filter,
  ListOrdered,
  Trophy,
} from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  'trending-up': TrendingUp,
  'sparkles': Sparkles,
  'printer': Printer,
  'timer': Timer,
  'calendar-days': CalendarDays,
  'circle-x': CircleX,
  'compass': Compass,
  'circle-check': CircleCheck,
  'shuffle': Shuffle,
  'graduation-cap': GraduationCap,
  'shield-check': ShieldCheck,
  'database': Database,
  'server': Server,
  'network': Network,
  'activity': Activity,
  'users': Users,
  'user': User,
  'user-cog': UserCog,
  'key': Key,
  'key-round': KeyRound,
  'lock': Lock,
  'tag': Tag,
  'tags': Tags,
  'wallet': Wallet,
  'coins': Coins,
  'folder-tree': FolderTree,
  'folder': Folder,
  'layers': Layers,
  'cloud': Cloud,
  'hard-drive': HardDrive,
  'globe': Globe,
  'router': Router,
  'split': Split,
  'scale': Scale,
  'shield': Shield,
  'shield-alert': ShieldAlert,
  'eye': Eye,
  'bell': Bell,
  'archive': Archive,
  'refresh-cw': RefreshCw,
  'box': Box,
  'boxes': Boxes,
  'container': Container,
  'app-window': AppWindow,
  'cpu': Cpu,
  'git-branch': GitBranch,
  'map': Map,
  'life-buoy': LifeBuoy,
  'file-text': FileText,
  'workflow': Workflow,
  'building': Building,
  'building-2': Building2,
  'landmark': Landmark,
  'gauge': Gauge,
  'brain': Brain,
  'flame': Flame,
  'target': Target,
  'clock': Clock,
  'zap': Zap,
  'waypoints': Waypoints,
  'cable': Cable,
  'route': Route,
  'radar': Radar,
  'scan-search': ScanSearch,
  'server-cog': ServerCog,
  'database-backup': DatabaseBackup,
  'hard-drive-download': HardDriveDownload,
  'cloud-cog': CloudCog,
  'fingerprint': Fingerprint,
  'id-card': IdCard,
  'badge-check': BadgeCheck,
  'scroll-text': ScrollText,
  'ban': Ban,
  'signpost': Signpost,
  'square-stack': SquareStack,
  'map-pin': MapPin,
  'lock-keyhole': LockKeyhole,
  'file-key': FileKey,
  'link-2': Link2,
  'repeat': Repeat,
  'gavel': Gavel,
  'circle-dollar-sign': CircleDollarSign,
  'antenna': Antenna,
  'plug-zap': PlugZap,
  'unplug': Unplug,
  'grid-2x2': Grid2x2,
  'spline': Spline,
  'monitor': Monitor,
  'lightbulb': Lightbulb,
  'triangle-alert': TriangleAlert,
  'book-open': BookOpen,
  'laptop': Laptop,
  'smartphone': Smartphone,
  'mail': Mail,
  'webhook': Webhook,
  'settings': Settings,
  'filter': Filter,
  'list-ordered': ListOrdered,
  'trophy': Trophy,
}

/**
 * Renders a content icon. "azure:<key>" names render the official Microsoft icon unmodified
 * (see src/content/azureIcons.ts for usage rules); anything else is a generic lucide icon.
 */
export function Icon({ name, ...props }: { name?: string } & LucideProps) {
  if (isAzureIcon(name)) {
    return <img src={azureIconUrl(name)} alt="" aria-hidden className={props.className} style={{ objectFit: 'contain' }} draggable={false} />
  }
  const C = (name && ICONS[name]) || Cloud
  return <C aria-hidden {...props} />
}
